# -*- coding: utf-8 -*-
"""skinDetect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zr5jXPZ5qMSuVdD9g48byKKjusx7ylA
"""

from PIL import Image
import numpy as NMP
import glob;
from google.colab import drive
drive.mount('/content/drive')

def probability(skinPixel, skin, nonSkinPixel, nonSkin):
  Pskin = NMP.zeros([256,256,256])
  PnSkin = NMP.zeros([256,256,256])
  Trained = NMP.zeros([256,256,256])
  file =open('/content/drive/MyDrive/dbms/result.txt','w')
  for i in range(256):
    for j in range(256):
        for k in range(256):
            Pskin[i][j][k]=skinPixel[i][j][k]/skin
            PnSkin[i][j][k]=nonSkinPixel[i][j][k]/nonSkin

            if PnSkin[i][j][k] == 0 and Pskin[i][j][k] == 0:
                file.write(str(0)+"\n")
            elif PnSkin[i][j][k] == 0:
                file.write(str(100)+"\n")
            else: 
                file.write(str(Pskin[i][j][k]/PnSkin[i][j][k])+"\n")

  file.close() 

def skinDet(imageArr, maskArr):
    skinPixel=NMP.zeros([256,256,256])
    nonSkinPixel = NMP.zeros([256,256,256])
    skin = 0.0
    nonSkin = 0.0

    for im in range(len(imageArr)):
        image = Image.open(imageArr[im])
        mask = Image.open(maskArr[im])
        for (imageP, maskP) in zip(image.getdata(),mask.getdata()):
          if  maskP[0] < 250 or  maskP[1] < 250 or  maskP[2] < 250:
              skinPixel[imageP[0]][imageP[1]][imageP[2]] += 1
              skin += 1
          else:
              nonSkinPixel[imageP[0]][imageP[1]][imageP[2]] += 1
              nonSkin += 1
    for im in range(len(imageArr)):
        image = Image.open(imageArr[im])
        mask = Image.open(maskArr[im])
    probability(skinPixel, skin, nonSkinPixel, nonSkin)
    

def main():
    imageArr = sorted(glob.glob("/content/drive/MyDrive/dbms/ibtd/*.jpg"))
    maskArr = sorted(glob.glob("/content/drive/MyDrive/dbms/ibtd/Mask/*.bmp"))
    skinDet(imageArr, maskArr)

if __name__ == '__main__':
    main()
